CREATE ROLE medico;
CREATE ROLE enfermera;
CREATE ROLE recepcionista;
CREATE ROLE administrador_informatico;
CREATE ROLE administrador_hospital;
CREATE ROLE conductor_ambulancia;

GRANT SELECT, INSERT, UPDATE, DELETE ON HISTORIAL_MEDICO TO medico;
GRANT SELECT, INSERT, UPDATE, DELETE ON DIAGNOSTICO TO medico;
GRANT SELECT, INSERT, UPDATE, DELETE ON RES_VIS TO medico;
GRANT SELECT ON EQUIPA TO medico;
GRANT SELECT ON HABITACION TO medico;
GRANT SELECT ON PLANTA TO medico;
GRANT SELECT ON QUIROFANO TO medico;

GRANT SELECT ON PACIENTE TO enfermera;
GRANT SELECT ON HISTORIAL_MEDICO TO enfermera;
GRANT SELECT ON DIAGNOSTICO TO enfermera;
GRANT SELECT ON RES_VIS TO enfermera;
GRANT SELECT ON HABITACION_VISITADA TO enfermera;
GRANT SELECT ON QUIROFANO_VISITADA TO enfermera;
GRANT SELECT ON QUIROFANO TO enfermera;
GRANT SELECT ON HABITACION TO enfermera;
GRANT SELECT ON EQUIPA TO enfermera;

GRANT SELECT ON RES_VIS TO recepcionista;
GRANT SELECT ON HABITACION_VISITADA TO recepcionista;
GRANT SELECT ON HABITACION TO recepcionista;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO administrador_informatico;

GRANT ALL PRIVILEGES ON PERSONAL TO administrador_hospital;
GRANT ALL PRIVILEGES ON EQUIPA TO administrador_hospital;

GRANT SELECT, INSERT ON RES_VIS TO conductor_ambulancia;
